docs_dir: docs/
repo_name: 'krai'
repo_url: 'https://github.com/krai'

site_name: 'LLM Finetuning'
site_description: 'LLM Finetuning 101'
site_author: 'Junfan Huang'
site_url: 'https://krai.ai'

edit_uri: edit/mkdocs/docs

# Copyright
copyright: 'Copyright &copy; 2023 KRAI'

# Navigation Page

nav:
  - Home: 
    - 'Home': index.md
    - 'Before FOSS Starts': installation.md
    - 'Schedule': schedule.md
    - 'Code of Conduct': code_of_conduct.md
    - 'Glossary & Acronyms': glossary.md
  - Lessons:
    - '0. LLM Introduction': 00_llm_intro.md
    - '1. Data Preparation': 01_data_prep.md
    - '2. Finetuning LLM': 02_llm_finetune.md
    - '3. Evaluate the Model': 03_model_evaluation.md
    - '4. Inside the Block Box': 04_black_box_enigma.md
    - '5. Version Control': 05_version_control.md
    - '6. Reproducibility I: Repeatability': 06_reproducibility_i.md
    - '7. Reproducibility II: Containers': 07_reproducibility_ii.md
  - Capstone Project:
      - 'Overview': final_project/overview.md

# must also set Action to use `@nomaterial` branch instead of `@master` for material
theme:
  name: material
# setting features for the navigation tab
  features:
    - navigation.instant
      #- navigation.expand
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Regular
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
  favicon: assets/favicon.png
  icon:
    logo: material/rocket

# Options
extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/
    - icon: fontawesome/brands/github
      link: https://github.com/cyverse-learning-material/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cyverseorg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cyverse.org
    - icon: fontawesome/brands/docker
      link: https://harbor.cyverse.org/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/CyverseOrgProject
  analytics:
    provider: google
    property: UA-72224033-6

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets

plugins:
    - search
    - inline-svg
    - mkdocstrings
    - git-revision-date
    - include-markdown
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True